name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Dependencies
        run: |
          yarn install
          cd nebulaview && yarn install

      - name: Build React App
        run: yarn build:react

      - name: Build and Release Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build:electron -p always