name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Root Dependencies
        run: yarn install

      - name: Install React Dependencies
        run: |
          cd nebulaview
          yarn install

      - name: Build React App
        run: |
          cd nebulaview
          CI=false yarn build

      - name: Build and Release Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build:electron -p always